// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: inbound_signal_messages.sql

package sqlc

import (
	"context"
)

const insertInbound = `-- name: InsertInbound :execrows
INSERT INTO signalium.inbound_signal_messages (
    source,
    source_uuid,
    source_timestamp,
    group_id,
    content,
    attachments,
    raw
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
ON CONFLICT (source, source_timestamp) DO NOTHING
`

type InsertInboundParams struct {
	Source          string
	SourceUuid      *string
	SourceTimestamp int64
	GroupID         *string
	Content         *string
	Attachments     []byte
	Raw             []byte
}

func (q *Queries) InsertInbound(ctx context.Context, arg InsertInboundParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertInbound,
		arg.Source,
		arg.SourceUuid,
		arg.SourceTimestamp,
		arg.GroupID,
		arg.Content,
		arg.Attachments,
		arg.Raw,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
