// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
	domain "github.com/olehmushka/go-signalium/internal/domain"
)

type SignaliumSignalMessageStatus string

const (
	SignaliumSignalMessageStatusPENDING         SignaliumSignalMessageStatus = "PENDING"
	SignaliumSignalMessageStatusSENDING         SignaliumSignalMessageStatus = "SENDING"
	SignaliumSignalMessageStatusSENT            SignaliumSignalMessageStatus = "SENT"
	SignaliumSignalMessageStatusFAILED          SignaliumSignalMessageStatus = "FAILED"
	SignaliumSignalMessageStatusPERMANENTFAILED SignaliumSignalMessageStatus = "PERMANENT_FAILED"
	SignaliumSignalMessageStatusTIMEDOUT        SignaliumSignalMessageStatus = "TIMED_OUT"
)

func (e *SignaliumSignalMessageStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SignaliumSignalMessageStatus(s)
	case string:
		*e = SignaliumSignalMessageStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for SignaliumSignalMessageStatus: %T", src)
	}
	return nil
}

type NullSignaliumSignalMessageStatus struct {
	SignaliumSignalMessageStatus SignaliumSignalMessageStatus
	Valid                        bool // Valid is true if SignaliumSignalMessageStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSignaliumSignalMessageStatus) Scan(value interface{}) error {
	if value == nil {
		ns.SignaliumSignalMessageStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SignaliumSignalMessageStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSignaliumSignalMessageStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SignaliumSignalMessageStatus), nil
}

type SignaliumInboundSignalMessage struct {
	InboundMessageID pgtype.UUID
	Source           string
	SourceUuid       *string
	SourceTimestamp  int64
	GroupID          *string
	Content          *string
	Attachments      []byte
	Raw              []byte
	ReceivedAt       pgtype.Timestamptz
	DeletedAt        pgtype.Timestamptz
}

type SignaliumSignalMessage struct {
	ID                pgtype.UUID
	ExternalID        string
	IdempotencyKey    *string
	Recipient         *string
	GroupID           *string
	SenderPhoneNumber string
	Content           string
	Attachments       domain.Attachments
	Attempts          int32
	MaxAttempts       int32
	NextAttemptAt     pgtype.Timestamptz
	TimeoutAt         pgtype.Timestamptz
	Status            domain.SignalMessageStatus
	LastError         *string
	ResultID          *string
	QuoteResultID     *string
	CorrelationID     string
	CreatedAt         pgtype.Timestamptz
	ModifiedAt        pgtype.Timestamptz
	DeletedAt         pgtype.Timestamptz
}
