// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	ClaimPending(ctx context.Context, leaseDuration pgtype.Interval) (*SignaliumSignalMessage, error)
	Count(ctx context.Context, arg CountParams) (int32, error)
	GetByExternalID(ctx context.Context, externalID string) (*SignaliumSignalMessage, error)
	GetByID(ctx context.Context, signalMessageID pgtype.UUID) (*SignaliumSignalMessage, error)
	GetByIdempotencyKey(ctx context.Context, idempotencyKey *string) (*SignaliumSignalMessage, error)
	Insert(ctx context.Context, arg InsertParams) (*SignaliumSignalMessage, error)
	InsertInbound(ctx context.Context, arg InsertInboundParams) (int64, error)
	List(ctx context.Context, arg ListParams) ([]*SignaliumSignalMessage, error)
	MarkFailed(ctx context.Context, arg MarkFailedParams) error
	MarkSent(ctx context.Context, arg MarkSentParams) error
	Resend(ctx context.Context, signalMessageID pgtype.UUID) error
	StatsCounts(ctx context.Context) ([]*StatsCountsRow, error)
	StatsPerDay(ctx context.Context) ([]*StatsPerDayRow, error)
	UpdateStatus(ctx context.Context, arg UpdateStatusParams) (*SignaliumSignalMessage, error)
}

var _ Querier = (*Queries)(nil)
