// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: signal_messages.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	domain "github.com/olehmushka/go-signalium/internal/domain"
)

const claimPending = `-- name: ClaimPending :one
WITH claimed AS (
  SELECT signal_message_id
    FROM signalium.signal_messages
   WHERE deleted_at IS NULL
     AND (status = 'PENDING' OR (status = 'SENDING' AND next_attempt_at < now()))
     AND next_attempt_at <= now()
   ORDER BY next_attempt_at
   FOR UPDATE SKIP LOCKED
   LIMIT 1
)
UPDATE signalium.signal_messages m
   SET status         = 'SENDING',
       attempts       = attempts + 1,
       next_attempt_at = now() + $1::interval,
       modified_at    = now()
  FROM claimed
 WHERE m.signal_message_id = claimed.signal_message_id
RETURNING m.signal_message_id, m.external_id, m.idempotency_key, m.recipient, m.group_id, m.sender_phone_number, m.content, m.attachments, m.attempts, m.max_attempts, m.next_attempt_at, m.timeout_at, m.status, m.last_error, m.result_id, m.quote_result_id, m.correlation_id, m.created_at, m.modified_at, m.deleted_at
`

func (q *Queries) ClaimPending(ctx context.Context, leaseDuration pgtype.Interval) (*SignaliumSignalMessage, error) {
	row := q.db.QueryRow(ctx, claimPending, leaseDuration)
	var i SignaliumSignalMessage
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.IdempotencyKey,
		&i.Recipient,
		&i.GroupID,
		&i.SenderPhoneNumber,
		&i.Content,
		&i.Attachments,
		&i.Attempts,
		&i.MaxAttempts,
		&i.NextAttemptAt,
		&i.TimeoutAt,
		&i.Status,
		&i.LastError,
		&i.ResultID,
		&i.QuoteResultID,
		&i.CorrelationID,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.DeletedAt,
	)
	return &i, err
}

const count = `-- name: Count :one
SELECT COUNT(*)::int AS counted
  FROM signalium.signal_messages
 WHERE deleted_at IS NULL
   AND ($1::text          IS NULL OR content    ILIKE '%' || $1::text || '%')
   AND ($2::signalium.signal_message_status IS NULL OR status = $2::signalium.signal_message_status)
   AND ($3::int    IS NULL OR attempts   = $3::int)
   AND ($4::timestamptz IS NULL OR created_at >= $4::timestamptz)
   AND ($5::timestamptz   IS NULL OR created_at <  $5::timestamptz)
`

type CountParams struct {
	Q             *string
	StatusFilter  *SignaliumSignalMessageStatus
	Attempts      *int32
	CreatedAtFrom pgtype.Timestamptz
	CreatedAtTo   pgtype.Timestamptz
}

func (q *Queries) Count(ctx context.Context, arg CountParams) (int32, error) {
	row := q.db.QueryRow(ctx, count,
		arg.Q,
		arg.StatusFilter,
		arg.Attempts,
		arg.CreatedAtFrom,
		arg.CreatedAtTo,
	)
	var counted int32
	err := row.Scan(&counted)
	return counted, err
}

const getByExternalID = `-- name: GetByExternalID :one
SELECT signal_message_id, external_id, idempotency_key, recipient, group_id, sender_phone_number, content, attachments, attempts, max_attempts, next_attempt_at, timeout_at, status, last_error, result_id, quote_result_id, correlation_id, created_at, modified_at, deleted_at FROM signalium.signal_messages
 WHERE external_id = $1
   AND deleted_at IS NULL
`

func (q *Queries) GetByExternalID(ctx context.Context, externalID string) (*SignaliumSignalMessage, error) {
	row := q.db.QueryRow(ctx, getByExternalID, externalID)
	var i SignaliumSignalMessage
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.IdempotencyKey,
		&i.Recipient,
		&i.GroupID,
		&i.SenderPhoneNumber,
		&i.Content,
		&i.Attachments,
		&i.Attempts,
		&i.MaxAttempts,
		&i.NextAttemptAt,
		&i.TimeoutAt,
		&i.Status,
		&i.LastError,
		&i.ResultID,
		&i.QuoteResultID,
		&i.CorrelationID,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.DeletedAt,
	)
	return &i, err
}

const getByID = `-- name: GetByID :one
SELECT signal_message_id, external_id, idempotency_key, recipient, group_id, sender_phone_number, content, attachments, attempts, max_attempts, next_attempt_at, timeout_at, status, last_error, result_id, quote_result_id, correlation_id, created_at, modified_at, deleted_at FROM signalium.signal_messages
 WHERE signal_message_id = $1
   AND deleted_at IS NULL
`

func (q *Queries) GetByID(ctx context.Context, signalMessageID pgtype.UUID) (*SignaliumSignalMessage, error) {
	row := q.db.QueryRow(ctx, getByID, signalMessageID)
	var i SignaliumSignalMessage
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.IdempotencyKey,
		&i.Recipient,
		&i.GroupID,
		&i.SenderPhoneNumber,
		&i.Content,
		&i.Attachments,
		&i.Attempts,
		&i.MaxAttempts,
		&i.NextAttemptAt,
		&i.TimeoutAt,
		&i.Status,
		&i.LastError,
		&i.ResultID,
		&i.QuoteResultID,
		&i.CorrelationID,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.DeletedAt,
	)
	return &i, err
}

const getByIdempotencyKey = `-- name: GetByIdempotencyKey :one
SELECT signal_message_id, external_id, idempotency_key, recipient, group_id, sender_phone_number, content, attachments, attempts, max_attempts, next_attempt_at, timeout_at, status, last_error, result_id, quote_result_id, correlation_id, created_at, modified_at, deleted_at FROM signalium.signal_messages
 WHERE idempotency_key = $1
`

func (q *Queries) GetByIdempotencyKey(ctx context.Context, idempotencyKey *string) (*SignaliumSignalMessage, error) {
	row := q.db.QueryRow(ctx, getByIdempotencyKey, idempotencyKey)
	var i SignaliumSignalMessage
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.IdempotencyKey,
		&i.Recipient,
		&i.GroupID,
		&i.SenderPhoneNumber,
		&i.Content,
		&i.Attachments,
		&i.Attempts,
		&i.MaxAttempts,
		&i.NextAttemptAt,
		&i.TimeoutAt,
		&i.Status,
		&i.LastError,
		&i.ResultID,
		&i.QuoteResultID,
		&i.CorrelationID,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.DeletedAt,
	)
	return &i, err
}

const insert = `-- name: Insert :one
INSERT INTO signalium.signal_messages (
    external_id,
    idempotency_key,
    recipient,
    group_id,
    sender_phone_number,
    content,
    attachments,
    max_attempts,
    timeout_at,
    correlation_id
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10
)
RETURNING signal_message_id, external_id, idempotency_key, recipient, group_id, sender_phone_number, content, attachments, attempts, max_attempts, next_attempt_at, timeout_at, status, last_error, result_id, quote_result_id, correlation_id, created_at, modified_at, deleted_at
`

type InsertParams struct {
	ExternalID        string
	IdempotencyKey    *string
	Recipient         *string
	GroupID           *string
	SenderPhoneNumber string
	Content           string
	Attachments       domain.Attachments
	MaxAttempts       int32
	TimeoutAt         pgtype.Timestamptz
	CorrelationID     string
}

func (q *Queries) Insert(ctx context.Context, arg InsertParams) (*SignaliumSignalMessage, error) {
	row := q.db.QueryRow(ctx, insert,
		arg.ExternalID,
		arg.IdempotencyKey,
		arg.Recipient,
		arg.GroupID,
		arg.SenderPhoneNumber,
		arg.Content,
		arg.Attachments,
		arg.MaxAttempts,
		arg.TimeoutAt,
		arg.CorrelationID,
	)
	var i SignaliumSignalMessage
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.IdempotencyKey,
		&i.Recipient,
		&i.GroupID,
		&i.SenderPhoneNumber,
		&i.Content,
		&i.Attachments,
		&i.Attempts,
		&i.MaxAttempts,
		&i.NextAttemptAt,
		&i.TimeoutAt,
		&i.Status,
		&i.LastError,
		&i.ResultID,
		&i.QuoteResultID,
		&i.CorrelationID,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.DeletedAt,
	)
	return &i, err
}

const list = `-- name: List :many
SELECT signal_message_id, external_id, idempotency_key, recipient, group_id, sender_phone_number, content, attachments, attempts, max_attempts, next_attempt_at, timeout_at, status, last_error, result_id, quote_result_id, correlation_id, created_at, modified_at, deleted_at
  FROM signalium.signal_messages
 WHERE deleted_at IS NULL
   AND ($1::text          IS NULL OR content    ILIKE '%' || $1::text || '%')
   AND ($2::signalium.signal_message_status IS NULL OR status = $2::signalium.signal_message_status)
   AND ($3::int    IS NULL OR attempts   = $3::int)
   AND ($4::timestamptz IS NULL OR created_at >= $4::timestamptz)
   AND ($5::timestamptz   IS NULL OR created_at <  $5::timestamptz)
 ORDER BY created_at DESC, signal_message_id ASC
 LIMIT  $7::int
 OFFSET $6::int
`

type ListParams struct {
	Q             *string
	StatusFilter  *SignaliumSignalMessageStatus
	Attempts      *int32
	CreatedAtFrom pgtype.Timestamptz
	CreatedAtTo   pgtype.Timestamptz
	OffsetCount   int32
	LimitCount    int32
}

func (q *Queries) List(ctx context.Context, arg ListParams) ([]*SignaliumSignalMessage, error) {
	rows, err := q.db.Query(ctx, list,
		arg.Q,
		arg.StatusFilter,
		arg.Attempts,
		arg.CreatedAtFrom,
		arg.CreatedAtTo,
		arg.OffsetCount,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*SignaliumSignalMessage{}
	for rows.Next() {
		var i SignaliumSignalMessage
		if err := rows.Scan(
			&i.ID,
			&i.ExternalID,
			&i.IdempotencyKey,
			&i.Recipient,
			&i.GroupID,
			&i.SenderPhoneNumber,
			&i.Content,
			&i.Attachments,
			&i.Attempts,
			&i.MaxAttempts,
			&i.NextAttemptAt,
			&i.TimeoutAt,
			&i.Status,
			&i.LastError,
			&i.ResultID,
			&i.QuoteResultID,
			&i.CorrelationID,
			&i.CreatedAt,
			&i.ModifiedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markFailed = `-- name: MarkFailed :exec
UPDATE signalium.signal_messages
   SET status = (CASE
                   WHEN attempts >= max_attempts THEN 'PERMANENT_FAILED'::signalium.signal_message_status
                   ELSE 'FAILED'::signalium.signal_message_status
                 END),
       last_error      = $1,
       next_attempt_at = $2,
       modified_at     = now()
 WHERE signal_message_id = $3
`

type MarkFailedParams struct {
	LastError     *string
	NextAttemptAt pgtype.Timestamptz
	ID            pgtype.UUID
}

func (q *Queries) MarkFailed(ctx context.Context, arg MarkFailedParams) error {
	_, err := q.db.Exec(ctx, markFailed, arg.LastError, arg.NextAttemptAt, arg.ID)
	return err
}

const markSent = `-- name: MarkSent :exec
UPDATE signalium.signal_messages
   SET status      = 'SENT',
       result_id   = $1,
       modified_at = now()
 WHERE signal_message_id = $2
`

type MarkSentParams struct {
	ResultID *string
	ID       pgtype.UUID
}

func (q *Queries) MarkSent(ctx context.Context, arg MarkSentParams) error {
	_, err := q.db.Exec(ctx, markSent, arg.ResultID, arg.ID)
	return err
}

const resend = `-- name: Resend :exec
UPDATE signalium.signal_messages
   SET status          = 'PENDING',
       attempts        = 0,
       next_attempt_at = now(),
       last_error      = NULL,
       modified_at     = now()
 WHERE signal_message_id = $1
   AND status IN ('FAILED', 'TIMED_OUT', 'PERMANENT_FAILED')
`

func (q *Queries) Resend(ctx context.Context, signalMessageID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, resend, signalMessageID)
	return err
}

const statsCounts = `-- name: StatsCounts :many
SELECT status,
       COUNT(*)::int AS counted
  FROM signalium.signal_messages
 WHERE deleted_at IS NULL
 GROUP BY status
`

type StatsCountsRow struct {
	Status  domain.SignalMessageStatus
	Counted int32
}

func (q *Queries) StatsCounts(ctx context.Context) ([]*StatsCountsRow, error) {
	rows, err := q.db.Query(ctx, statsCounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*StatsCountsRow{}
	for rows.Next() {
		var i StatsCountsRow
		if err := rows.Scan(&i.Status, &i.Counted); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const statsPerDay = `-- name: StatsPerDay :many
SELECT to_char(date_trunc('day', created_at), 'YYYY-MM-DD')                                     AS day,
       COUNT(*) FILTER (WHERE status = 'SENT')::int                                              AS sent,
       COUNT(*) FILTER (WHERE status IN ('FAILED', 'PERMANENT_FAILED', 'TIMED_OUT'))::int        AS failed
  FROM signalium.signal_messages
 WHERE deleted_at IS NULL
   AND created_at >= now() - interval '30 days'
 GROUP BY day
 ORDER BY day
`

type StatsPerDayRow struct {
	Day    string
	Sent   int32
	Failed int32
}

func (q *Queries) StatsPerDay(ctx context.Context) ([]*StatsPerDayRow, error) {
	rows, err := q.db.Query(ctx, statsPerDay)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*StatsPerDayRow{}
	for rows.Next() {
		var i StatsPerDayRow
		if err := rows.Scan(&i.Day, &i.Sent, &i.Failed); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStatus = `-- name: UpdateStatus :one
UPDATE signalium.signal_messages
   SET status      = $1,
       modified_at = now()
 WHERE signal_message_id = $2
   AND deleted_at IS NULL
RETURNING signal_message_id, external_id, idempotency_key, recipient, group_id, sender_phone_number, content, attachments, attempts, max_attempts, next_attempt_at, timeout_at, status, last_error, result_id, quote_result_id, correlation_id, created_at, modified_at, deleted_at
`

type UpdateStatusParams struct {
	Status domain.SignalMessageStatus
	ID     pgtype.UUID
}

func (q *Queries) UpdateStatus(ctx context.Context, arg UpdateStatusParams) (*SignaliumSignalMessage, error) {
	row := q.db.QueryRow(ctx, updateStatus, arg.Status, arg.ID)
	var i SignaliumSignalMessage
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.IdempotencyKey,
		&i.Recipient,
		&i.GroupID,
		&i.SenderPhoneNumber,
		&i.Content,
		&i.Attachments,
		&i.Attempts,
		&i.MaxAttempts,
		&i.NextAttemptAt,
		&i.TimeoutAt,
		&i.Status,
		&i.LastError,
		&i.ResultID,
		&i.QuoteResultID,
		&i.CorrelationID,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.DeletedAt,
	)
	return &i, err
}
